-- 20260224130000_add_consent_deleted_at
-- This migration was originally adding soft-delete support (`deleted_at`) to the `consents` table.
-- That column and its index were later removed from the data model.
-- We intentionally leave this migration empty so the final schema does not include `deleted_at`.
